### ISSUE TITLE
Showing Schemes doesn't work on WSL

### ISSUE THREAD

**Issue by zadjii-msft** [Microsoft/console#312]
From #22:
> 
> 
> @Falcury `-q -x` works for me, though showing schemes does not:
> 
> ```shell
> [rofrol@DESKTOP-NBALJ88 ~]$ pushd ~/rofrol/installed/colortool/ &> /dev/null
> [rofrol@DESKTOP-NBALJ88 ~/rofrol/installed/colortool]$ ./colortool.exe -s
> 
> Unhandled Exception: System.IO.IOException: The handle is invalid.
> 
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
>    at System.Console.get_WindowWidth()
>    at ColorTool.Program.PrintSchemes()
>    at ColorTool.Program.Main(String[] args)
> ```

This should be fixed. 
* [ ] We need to add support for `-s -x` to print the scemes in linux-y mode
* [ ] We should probably also catch this exception for the `-s` flag and properly display an error along the lines of "You should try `-s -x`"

**Comment by E3V3A** [comment]
Same problem when running under Cygwin. 
Also Mintty doesn't show the color codes: 

```bash
# ColorTool.exe -c                                                                                                                                             40m     41m     42m     43m     44m     45m     46m     47m                                                                m         gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw                                                                1m        gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw                                                                30m       gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw                                                                1;30m     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw                                                                31m       gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw                                                                1;31m     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw                                                                32m       gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw                                                                1;32m     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw                                                                33m       gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw                                                                1;33m     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw                                                                34m       gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw                                                                1;34m     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw                                                                35m       gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw                                                                1;35m     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw                                                                36m       gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw                                                                1;36m     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw                                                                37m       gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw                                                                1;37m     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw     gYw
```
